sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
      # - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  # only:
  #   - master

services: docker

env:
  matrix:
  - INSTANCE=default-centos-7
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-centos-7 CHEF_VERSION=12.7.2
  - INSTANCE=default-ubuntu-1604 CHEF_VERSION=12.7.2
  - INSTANCE=resource-centos-7
  - INSTANCE=resource-ubuntu-1604
  - INSTANCE=resource-centos-7 CHEF_VERSION=12.7.2
  - INSTANCE=resource-ubuntu-1604 CHEF_VERSION=12.7.2
  - INSTANCE=api-centos-7
  - INSTANCE=api-centos-7 CHEF_VERSION=12.7.2

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - /opt/chefdk/bin/chef gem install net-http-digest_auth --no-document
      - /opt/chefdk/bin/chef exec delivery local lint
      - /opt/chefdk/bin/chef exec delivery local syntax
      - /opt/chefdk/bin/chef exec delivery local unit

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/dc143a4bf4fb95b75249
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
